image: nixos/nix

before_script:
  - nix-channel --add https://gitlab.com/serokell/nixpkgs/-/archive/master/nixpkgs-master.tar.gz nixpkgs 
  - nix-channel --update

ipxe:
  script:
  - nix-build all-at-once.nix
  - aws s3 cp --endpoint-url=https://s3.wasabisys.com --recursive result s3://nixos-packet
  only:
  - master
